### ISSUE TITLE
good suggetion

### ISSUE THREAD

**Issue by promarcos** [Philipp15b/MagicSigns#6]
suggestion:
create a file to save the texts.

So well with the plugin SignLink: http://dev.bukkit.org/server-mods/signlink/
The signs could load the texts, the classic form, not as in SignLink, where the text is a sing to another.
sample file:
texts:
   '1 ':
        line1: &1this
        line2: &2&lcoool
        line3: \* form *
        line4: edit sign
   '2 ':
       line1: [cmd]
        line2: &2&lcoool
        line3: \* form *
        line4: edit commands

So in the game, the admin could just load the text typing something on the board:
eg

  %FText [id]

and the plate would load the text.

This would be a form, to edit a large number of signs, at the same time, anywhere, without the need of being logged.

**Comment by Philipp15b** [comment]
So to understand this correctly. You want to save sign texts in a file and you want to be able to load them on a sign with just typing an id. This is possible. But you also want to be able to edit all these signs that use a predefined text by changing the config? I see a problem there because that would result in a huge load of block changes and chunk loads everytime the config is loaded (which would be at startup) because MagicSigns would have to search and compare them to these to the config.

**Comment by promarcos** [comment]
Suffice it to load at startup
when the server was started
eg
I would make a tutorial area, with many signs
but instead of editing out one by one, as in the classical manner.

I would edit the text in config.yml file.
type into the console magicsings reload.
and within the server I put the signs with texts previously configured in file, as its id.

**Comment by Philipp15b** [comment]
I decided to not implement this in the near future. MagicSigns is all about signs that interact with the user, not an admin tool. Also - as said above - this would make chunk loads even slower than they already are in Minecraft.
